version: '2'
services:

  web:
    container_name: nginx
    image: nginx
    restart: always
    #links:
    #  - php:php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #- "../src/yii-application/:/data/web/"
      - "../src/basic/:/data/web/"
      - "./nginx_conf/:/etc/nginx/"
      - "./nginx_log/:/var/log/nginx/"
      - "/etc/localtime:/etc/localtime"
      - "sock_php:/var/run"  
    networks:
      - backend_php

  php:
    container_name: php-fpm 
    build: ./php_build
    #container_name: php_yii2
    #build: ./php_yii2_build
    #image: php:fpm
    links:
      - db:db
    # - mq:mq
      - redis:redis
    volumes:
      #- "../src/yii-application/:/data/web/"
      - "../src/basic/:/data/web/"
      - "./php_log/:/usr/local/var/log/"
      - "./php_conf/:/usr/local/etc/"
      - "/etc/localtime:/etc/localtime"
      - "sock_php:/var/run"  
    networks:
      - backend_php
  #mq:
  #  container_name: rabbitmq
  #  image: rabbitmq
  
  db:
    container_name: mysql
    image: mysql
    environment:
        MYSQL_DATABASE: db_findata
        MYSQL_ROOT_PASSWORD: 1234rewq
    ports:
      - "33060:3306"
    volumes:
      - "./mysql_file/:/var/lib/mysql"
      - "./mysql_conf/:/etc/mysql/"
      - "/etc/localtime:/etc/localtime"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6499:6379"
    volumes:
      - "/etc/localtime:/etc/localtime"

        
networks:
    backend_php:
        driver: bridge
volumes:
    sock_php:
